ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'MFA_ENROLLMENT_STARTED';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'PASSWORD_CHANGED';
ALTER TABLE "AdministratorMfaMethod" ADD COLUMN "verifiedAt" TIMESTAMP(3), ADD COLUMN "disabledAt" TIMESTAMP(3);
