import { NextResponse } from "next/server";
import { z } from "zod";
import { requireUser } from "@/lib/auth";
import { requireAccountAccess, roleHasCapability } from "@/lib/authorization";
import { db } from "@/lib/db";
import { apiError } from "@/lib/http";
import { assertSameOrigin } from "@/lib/security/request";
import { updateOrganizationProfile } from "@/lib/organizations";
const schema = z.object({ displayName: z.string().trim().min(2).max(120).optional(), legalName: z.string().trim().min(2).max(180).optional(), billingEmail: z.string().trim().email().optional(), registrationNumber: z.string().trim().max(80).nullable().optional(), taxId: z.string().trim().max(80).nullable().optional() }).strict();
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await requireUser(); const { id } = await params; const access = await requireAccountAccess(user.id, id); const canManageMembers = roleHasCapability(access.effectiveRole, "MANAGE_MEMBERS"); const canViewBilling = roleHasCapability(access.effectiveRole, "VIEW_PAYMENTS"); const canViewLicenses = roleHasCapability(access.effectiveRole, "VIEW_LICENSES"); const account = await db.customerAccount.findUniqueOrThrow({ where: { id }, include: { organization: true, memberships: { include: { user: { select: { id: true, email: true, name: true } } }, orderBy: { createdAt: "asc" } }, invitations: canManageMembers ? { where: { status: "PENDING" }, orderBy: { createdAt: "desc" } } : false, _count: { select: { licenses: true, subscriptions: true, orders: true } } } }); return NextResponse.json({ id: account.id, type: account.type, displayName: account.displayName, lifecycleState: account.lifecycleState, role: access.effectiveRole, organization: account.organization, billingEmail: canViewBilling ? account.billingEmail : null, taxId: canViewBilling ? account.taxId : null, counts: { licenses: canViewLicenses ? account._count.licenses : null, subscriptions: canViewBilling || canViewLicenses ? account._count.subscriptions : null, orders: canViewBilling ? account._count.orders : null }, memberships: canManageMembers ? account.memberships.map((m) => ({ userId: m.userId, role: m.role, email: m.user.email, name: m.user.name })) : [], invitations: canManageMembers ? account.invitations : [] }); } catch (error) { return apiError(error); } }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { assertSameOrigin(request); const user = await requireUser(); const { id } = await params; const input = schema.parse(await request.json()); const account = await updateOrganizationProfile({ actorId: user.id, accountId: id, ...input }); return NextResponse.json({ id: account.id }); } catch (error) { return apiError(error); } }
