import "dotenv/config";
import { createHmac } from "node:crypto";
import { test, expect } from "@playwright/test";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../../generated/prisma/client";

const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL!})});
test.beforeAll(async()=>{const{createClient}=await import("redis");const redis=createClient({url:process.env.REDIS_URL});await redis.connect();await redis.flushDb();await redis.quit()});
test.afterAll(()=>db.$disconnect());

test("verified customer completes purchase, download, activation, renewal, and cancellation",async({page})=>{
  const suffix=Date.now().toString(36);const email=`browser-${suffix}@bke.test`;const password="Browser-Test-2026!";
  await page.goto("/register");await page.getByLabel("Full name").fill("Browser Customer");await page.getByLabel("Email address").fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Create account"}).click();await expect(page).toHaveURL(/verify-email/);
  const user=await db.user.findUniqueOrThrow({where:{email},include:{ownedAccounts:true}});const accountId=user.ownedAccounts[0]!.id;const verifyToken=`verify-${suffix}`;const tokenHash=createHmac("sha256",process.env.SESSION_SECRET!).update(verifyToken).digest("hex");await db.verificationToken.deleteMany({where:{identifier:email,purpose:"VERIFY_EMAIL"}});await db.verificationToken.create({data:{identifier:email,purpose:"VERIFY_EMAIL",tokenHash,expiresAt:new Date(Date.now()+60000)}});await page.goto(`/api/auth/verify?token=${verifyToken}`);await expect(page).toHaveURL(/dashboard/);
  await page.evaluate(()=>fetch("/api/auth/logout",{method:"POST"}));await page.goto("/login");await page.getByLabel("Email address").first().fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Sign in"}).click();await expect(page).toHaveURL(/dashboard/);
  const price=await db.price.findFirstOrThrow({where:{product:{slug:"bke-cloudops"},active:true}});const checkout=await page.evaluate(async(input)=>{const r=await fetch("/api/checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)});return{status:r.status,body:await r.json()}},{accountId,items:[{priceId:price.id,quantity:1}]});expect(checkout.status).toBe(201);const order=await db.order.findUniqueOrThrow({where:{id:checkout.body.orderId},include:{attempts:true}});
  const event={eventId:`evt_browser_${order.id}`,type:"payment.paid",externalPaymentId:`pay_browser_${order.id}`,externalCheckoutId:order.attempts[0]!.externalCheckoutId,reference:order.number,amountMinor:order.totalMinor,currency:order.currency,livemode:false,occurredAt:new Date().toISOString()};const raw=JSON.stringify(event);const signature=createHmac("sha256",process.env.SESSION_SECRET!).update(raw).digest("hex");const hook=await page.request.post("/api/webhooks/payments",{data:raw,headers:{"content-type":"application/json","x-mock-signature":signature}});expect(hook.status()).toBe(200);
  const paid=await db.order.findUniqueOrThrow({where:{id:order.id},include:{invoice:true,licenses:true,subscriptions:true}});expect(paid.status).toBe("PAID");expect(paid.invoice?.status).toBe("FINAL");expect(paid.licenses).toHaveLength(1);expect(paid.subscriptions).toHaveLength(1);
  const reveal=await page.evaluate(async(id)=>{const r=await fetch(`/api/licenses/${id}/reveal`,{method:"POST"});return{status:r.status,body:await r.json()}},paid.licenses[0]!.id);expect(reveal.status).toBe(200);expect(reveal.body.licenseKey).toMatch(/^BKE-/);const revealAgain=await page.evaluate(async(id)=>(await fetch(`/api/licenses/${id}/reveal`,{method:"POST"})).status,paid.licenses[0]!.id);expect(revealAgain).toBe(409);
  const activation=await page.request.post("/api/licenses/activate",{data:{licenseKey:reveal.body.licenseKey,deviceId:`browser-device-${suffix}`}});expect(activation.status()).toBe(200);
  const artifact=await db.productArtifact.findUniqueOrThrow({where:{objectKey:"installers/bke-installer.bin"}});const beforeDownloads=artifact.downloadCount;const grant=await page.request.get(`/api/downloads/${artifact.id}`,{maxRedirects:0});expect(grant.status()).toBe(303);const location=grant.headers().location!;const download=await page.request.get(location,{maxRedirects:0});expect(download.status()).toBe(200);expect((await download.body()).toString("utf8")).toContain("BKE Digital Solutions test installer");expect((await db.productArtifact.findUniqueOrThrow({where:{id:artifact.id}})).downloadCount).toBe(beforeDownloads+1);expect((await page.request.get(location,{maxRedirects:0})).status()).toBe(404);expect((await page.request.get(`${location.slice(0,-1)}x`,{maxRedirects:0})).status()).toBe(404);
  const renewal=await page.evaluate(async(id)=>{const r=await fetch(`/api/subscriptions/${id}/renew`,{method:"POST"});return{status:r.status,body:await r.json()}},paid.subscriptions[0]!.id);expect(renewal.status).toBe(201);const cancellation=await page.evaluate(async(id)=>{const r=await fetch(`/api/orders/${id}/cancel`,{method:"POST"});return{status:r.status,body:await r.json()}},renewal.body.orderId);expect(cancellation).toEqual({status:200,body:{status:"CANCELLED"}});
  await page.goto("/admin");await expect(page).toHaveURL(/login/);
});

test("a second customer cannot enumerate another account",async({page})=>{
  const owned=await db.order.findFirstOrThrow({where:{status:"PAID"},include:{items:true}});const suffix=Date.now().toString(36);const email=`outsider-browser-${suffix}@bke.test`;await page.goto("/register");await page.getByLabel("Full name").fill("Outside Customer");await page.getByLabel("Email address").fill(email);await page.getByLabel("Password").fill("Outside-Test-2026!");await page.getByRole("button",{name:"Create account"}).click();await expect(page).toHaveURL(/verify-email/);await db.user.update({where:{email},data:{emailVerified:new Date()}});
  expect((await page.request.get(`/api/orders/${owned.id}`)).status()).toBe(404);const artifact=await db.productArtifact.findUniqueOrThrow({where:{objectKey:"installers/bke-installer.bin"}});expect((await page.request.get(`/api/downloads/${artifact.id}`,{maxRedirects:0})).status()).toBe(404);await page.goto("/admin");await expect(page).toHaveURL(/login/);
});
