import "dotenv/config";
import { createHmac } from "node:crypto";
import { test, expect } from "@playwright/test";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../../generated/prisma/client";

const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL!})});
test.beforeAll(async()=>{const{createClient}=await import("redis");const redis=createClient({url:process.env.REDIS_URL});await redis.connect();await redis.flushDb();await redis.quit()});
test.afterAll(()=>db.$disconnect());

test("verified customer completes purchase, download, activation, renewal, and cancellation",async({page})=>{
  const suffix=Date.now().toString(36);const email=`browser-${suffix}@bke.test`;const password="Browser-Test-2026!";
  await page.goto("/register");await page.getByLabel("Full name").fill("Browser Customer");await page.getByLabel("Email address").fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Create account"}).click();await expect(page).toHaveURL(/verify-email/,{timeout:30_000});await expect(page.getByRole("button",{name:"Resend verification email"})).toBeVisible();
  const user=await db.user.findUniqueOrThrow({where:{email},include:{ownedAccounts:true}});const accountId=user.ownedAccounts[0]!.id;const verifyToken=`verify-${suffix}`;const tokenHash=createHmac("sha256",process.env.SESSION_SECRET!).update(verifyToken).digest("hex");await db.verificationToken.deleteMany({where:{identifier:email,purpose:"VERIFY_EMAIL"}});await db.verificationToken.create({data:{identifier:email,purpose:"VERIFY_EMAIL",tokenHash,expiresAt:new Date(Date.now()+60000)}});await page.goto(`/api/auth/verify?token=${verifyToken}`);await expect(page).toHaveURL(/dashboard/);
  await page.evaluate(()=>fetch("/api/auth/logout",{method:"POST"}));await page.goto("/login");await page.getByLabel("Email address").first().fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Sign in"}).click();await expect(page).toHaveURL(/dashboard/);
  await page.goto("/products/bke-deskflow");await page.getByRole("button",{name:"Start free 7-day trial"}).first().click();await expect(page).toHaveURL(/dashboard/);const trial=await db.trialGrant.findFirstOrThrow({where:{accountId,product:{slug:"bke-deskflow"}},include:{license:true}});expect(trial.license.status).toBe("ACTIVE");expect(trial.trialEndsAt.getTime()-trial.trialStartsAt.getTime()).toBe(7*86400000);const repeatedTrial=await page.evaluate(async input=>{const response=await fetch("/api/trials",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)});return{status:response.status,body:await response.json()}},{editionId:trial.editionId,accountId});expect(repeatedTrial.status).toBe(400);expect(repeatedTrial.body.error).toBe("TRIAL_ALREADY_USED_THIS_YEAR");
  const plan=await db.purchasePlan.findFirstOrThrow({where:{edition:{product:{slug:"bke-cloudops"}},type:"ANNUAL",active:true}});const checkout=await page.evaluate(async(input)=>{const r=await fetch("/api/checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)});return{status:r.status,body:await r.json()}},{purchasePlanId:plan.id,customerAccountId:accountId});expect(checkout.status).toBe(201);const order=await db.order.findUniqueOrThrow({where:{id:checkout.body.orderId},include:{attempts:true}});expect(order.accountId).toBe(accountId);await db.paymentAttempt.update({where:{id:order.attempts[0]!.id},data:{checkoutUrl:null}});const resumed=await page.evaluate(async(id)=>{const r=await fetch(`/api/orders/${id}/continue`,{method:"POST"});return{status:r.status,body:await r.json()}},order.id);expect(resumed.status).toBe(200);expect(resumed.body.checkoutUrl).toContain("/checkout/mock");const resumedAgain=await page.evaluate(async(id)=>{const r=await fetch(`/api/orders/${id}/continue`,{method:"POST"});return{status:r.status,body:await r.json()}},order.id);expect(resumedAgain).toEqual(resumed);expect(await db.paymentAttempt.count({where:{orderId:order.id}})).toBe(2);
  const event={eventId:`evt_browser_${order.id}`,type:"payment.paid",externalPaymentId:`pay_browser_${order.id}`,externalCheckoutId:order.attempts[0]!.externalCheckoutId,reference:order.number,amountMinor:order.totalMinor,currency:order.currency,livemode:false,occurredAt:new Date().toISOString()};const raw=JSON.stringify(event);const signature=createHmac("sha256",process.env.SESSION_SECRET!).update(raw).digest("hex");const hook=await page.request.post("/api/webhooks/payments",{data:raw,headers:{"content-type":"application/json","x-mock-signature":signature}});expect(hook.status()).toBe(200);
  const paid=await db.order.findUniqueOrThrow({where:{id:order.id},include:{invoice:true,licenses:true,subscriptions:true}});expect(paid.status).toBe("PAID");expect(paid.invoice?.status).toBe("FINAL");expect(paid.licenses).toHaveLength(1);expect(paid.subscriptions).toHaveLength(1);
  const reveal=await page.evaluate(async(id)=>{const r=await fetch(`/api/licenses/${id}/reveal`,{method:"POST"});return{status:r.status,body:await r.json()}},paid.licenses[0]!.id);expect(reveal.status).toBe(200);expect(reveal.body.licenseKey).toMatch(/^BKE-/);const revealAgain=await page.evaluate(async(id)=>{const r=await fetch(`/api/licenses/${id}/reveal`,{method:"POST"});return{status:r.status,body:await r.json()}},paid.licenses[0]!.id);expect(revealAgain.status).toBe(200);expect(revealAgain.body.licenseKey).toBe(reveal.body.licenseKey);expect(await db.licenseEvent.count({where:{licenseId:paid.licenses[0]!.id,type:"CUSTOMER_REVEALED"}})).toBe(2);
  const activation=await page.request.post("/api/licenses/activate",{data:{licenseKey:reveal.body.licenseKey,deviceId:`browser-device-${suffix}`}});expect(activation.status()).toBe(200);
  const artifact=await db.productArtifact.findUniqueOrThrow({where:{objectKey:"installers/bke-installer.bin"}});const beforeDownloads=artifact.downloadCount;const revokedGrant=await page.request.get(`/api/downloads/${artifact.id}`,{maxRedirects:0});expect(revokedGrant.status()).toBe(303);await db.license.update({where:{id:paid.licenses[0]!.id},data:{status:"REVOKED"}});expect((await page.request.get(revokedGrant.headers().location!,{maxRedirects:0})).status()).toBe(404);await db.license.update({where:{id:paid.licenses[0]!.id},data:{status:"ACTIVE"}});const grant=await page.request.get(`/api/downloads/${artifact.id}`,{maxRedirects:0});expect(grant.status()).toBe(303);const location=grant.headers().location!;const download=await page.request.get(location,{maxRedirects:0});expect(download.status()).toBe(200);expect((await download.body()).toString("utf8")).toContain("BKE Digital Solutions test installer");expect((await db.productArtifact.findUniqueOrThrow({where:{id:artifact.id}})).downloadCount).toBe(beforeDownloads+1);expect((await page.request.get(location,{maxRedirects:0})).status()).toBe(404);expect((await page.request.get(`${location.slice(0,-1)}x`,{maxRedirects:0})).status()).toBe(404);
  const renewal=await page.evaluate(async(id)=>{const r=await fetch(`/api/subscriptions/${id}/renew`,{method:"POST"});return{status:r.status,body:await r.json()}},paid.subscriptions[0]!.id);expect(renewal.status).toBe(201);const renewalOrder=await db.order.findUniqueOrThrow({where:{id:renewal.body.orderId},include:{attempts:true}});const cancellation=await page.evaluate(async(id)=>{const r=await fetch(`/api/orders/${id}/cancel`,{method:"POST"});return{status:r.status,body:await r.json()}},renewal.body.orderId);expect(cancellation).toEqual({status:200,body:{status:"CANCELLED"}});const lateEvent={eventId:`evt_late_${renewalOrder.id}`,type:"payment.paid",externalPaymentId:`pay_late_${renewalOrder.id}`,externalCheckoutId:renewalOrder.attempts[0]!.externalCheckoutId,reference:renewalOrder.number,amountMinor:renewalOrder.totalMinor,currency:renewalOrder.currency,livemode:false,occurredAt:new Date().toISOString()};const lateRaw=JSON.stringify(lateEvent);const lateSignature=createHmac("sha256",process.env.SESSION_SECRET!).update(lateRaw).digest("hex");expect((await page.request.post("/api/webhooks/payments",{data:lateRaw,headers:{"content-type":"application/json","x-mock-signature":lateSignature}})).status()).toBe(200);expect((await db.order.findUniqueOrThrow({where:{id:renewalOrder.id}})).status).toBe("PAID");expect(await db.license.count({where:{subscriptionId:paid.subscriptions[0]!.id}})).toBe(1);
  await page.goto("/admin");await expect(page).toHaveURL(/login/);
});

test("a second customer cannot enumerate another account",async({page})=>{
  const owned=await db.order.findFirstOrThrow({where:{status:"PAID"},include:{items:true}});const suffix=Date.now().toString(36);const email=`outsider-browser-${suffix}@bke.test`;await page.goto("/register");await page.getByLabel("Full name").fill("Outside Customer");await page.getByLabel("Email address").fill(email);await page.getByLabel("Password").fill("Outside-Test-2026!");await page.getByRole("button",{name:"Create account"}).click();await expect(page).toHaveURL(/verify-email/);await db.user.update({where:{email},data:{emailVerified:new Date()}});
  expect((await page.request.get(`/api/orders/${owned.id}`)).status()).toBe(404);const artifact=await db.productArtifact.findUniqueOrThrow({where:{objectKey:"installers/bke-installer.bin"}});expect((await page.request.get(`/api/downloads/${artifact.id}`,{maxRedirects:0})).status()).toBe(404);await page.goto("/admin");await expect(page).toHaveURL(/login/);
});
