import "dotenv/config";
import { createHmac } from "node:crypto";
import { describe, expect, it, vi } from "vitest";

const secret="sandbox-webhook-secret";
function signed(body:object,timestamp=Math.floor(Date.now()/1000)){const raw=Buffer.from(JSON.stringify(body));const signature=createHmac("sha256",secret).update(`${timestamp}.${raw.toString("utf8")}`).digest("hex");return{raw,headers:new Headers({"paymongo-signature":`t=${timestamp},te=${signature},li=unused`})}}

describe("PayMongo event normalization",()=>{
  it("refuses a live key when configured for test mode",async()=>{const{PayMongoProvider}=await import("@/lib/payments/paymongo");const provider=new PayMongoProvider({secretKey:"sk_live_unsafe",webhookSecret:secret,livemode:false});await expect(provider.retrievePayment("pay_test")).rejects.toThrow("PAYMENT_PROVIDER_UNSAFE_CONFIGURATION")});
  it("normalizes checkout-session paid events without logging the raw payload",async()=>{const consoleSpies=[vi.spyOn(console,"info"),vi.spyOn(console,"warn"),vi.spyOn(console,"error")];const{PayMongoProvider}=await import("@/lib/payments/paymongo");const provider=new PayMongoProvider({secretKey:"sk_test_placeholder",webhookSecret:secret,livemode:false});const input=signed({data:{id:"evt_test_paid",attributes:{type:"checkout_session.payment.paid",livemode:false,created_at:Math.floor(Date.now()/1000),data:{id:"cs_test",type:"checkout_session",attributes:{reference_number:"BKE-TEST",payments:[{id:"pay_test",type:"payment",attributes:{amount:10000,currency:"PHP"}}]}}}}});const event=await provider.verifyAndParseWebhook(input.raw,input.headers);expect(event).toMatchObject({eventId:"evt_test_paid",type:"payment.paid",externalPaymentId:"pay_test",externalCheckoutId:"cs_test",reference:"BKE-TEST",amountMinor:10000,currency:"PHP",livemode:false});expect(consoleSpies.every(spy=>spy.mock.calls.length===0)).toBe(true);consoleSpies.forEach(spy=>spy.mockRestore())});
  it("normalizes payment failures and refunds",async()=>{const{PayMongoProvider}=await import("@/lib/payments/paymongo");const provider=new PayMongoProvider({secretKey:"sk_test_placeholder",webhookSecret:secret,livemode:false});for(const[type,expected]of [["payment.failed","payment.failed"],["payment.refunded","payment.refunded"]] as const){const input=signed({data:{id:`evt_${expected}`,attributes:{type,livemode:false,created_at:Math.floor(Date.now()/1000),data:{id:"pay_test",type:"payment",attributes:{amount:10000,currency:"PHP",external_reference_number:"BKE-TEST",checkout_session_id:"cs_test"}}}}});expect((await provider.verifyAndParseWebhook(input.raw,input.headers)).type).toBe(expected)}});
  it("rejects stale and invalid signatures",async()=>{const{PayMongoProvider}=await import("@/lib/payments/paymongo");const provider=new PayMongoProvider({secretKey:"sk_test_placeholder",webhookSecret:secret,livemode:false});const body={data:{id:"evt_stale",attributes:{type:"payment.paid",livemode:false,created_at:1,data:{id:"pay_test",type:"payment",attributes:{amount:10000,currency:"PHP"}}}}};const stale=signed(body,Math.floor(Date.now()/1000)-301);await expect(provider.verifyAndParseWebhook(stale.raw,stale.headers)).rejects.toThrow("INVALID_SIGNATURE");await expect(provider.verifyAndParseWebhook(Buffer.from(JSON.stringify(body)),new Headers({"paymongo-signature":`t=${Math.floor(Date.now()/1000)},te=forged`}))).rejects.toThrow("INVALID_SIGNATURE")});
  it("accepts a delayed event when PayMongo signs the retry with a fresh timestamp",async()=>{const{PayMongoProvider}=await import("@/lib/payments/paymongo");const provider=new PayMongoProvider({secretKey:"sk_test_placeholder",webhookSecret:secret,livemode:false});const input=signed({data:{id:"evt_delayed",attributes:{type:"payment.failed",livemode:false,created_at:Math.floor(Date.now()/1000)-86400,data:{id:"pay_delayed",type:"payment",attributes:{amount:10000,currency:"PHP"}}}}});const event=await provider.verifyAndParseWebhook(input.raw,input.headers);expect(event.type).toBe("payment.failed");expect(event.occurredAt.getTime()).toBeLessThan(Date.now()-86000_000)});
});
