import { AdminActionButton } from "@/components/admin-action-button";
import { db } from "@/lib/db";
import { requireAdmin } from "@/lib/auth";

export default async function SupplyChainPage() {
  await requireAdmin();
  const rows = await db.supplyChainEvidence.findMany({ include: { version: { include: { product: true, artifacts: true } } }, orderBy: { builtAt: "desc" } });
  return <main className="shell py-10"><h1 className="text-4xl font-black">Software supply chain</h1><p className="mt-2 text-slate-600">Release integrity evidence. Malware scans inspect the current private artifact bytes and remain independent from signing.</p><div className="mt-8 overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead><tr className="border-b bg-slate-50"><th className="p-3">Release</th><th className="p-3">SBOM</th><th className="p-3">Signature</th><th className="p-3">Dependencies</th><th className="p-3">Malware</th><th className="p-3">Certificates</th><th className="p-3">Actions</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id} className="border-b"><td className="p-3 font-bold">{r.version.product.name} {r.version.version}</td><td className="p-3">{r.sbomReference ? "Available" : "Missing"}</td><td className="p-3">{r.signatureVerified ? `Verified (${r.signatureKeyId ?? "legacy"})` : "Pending"}</td><td className="p-3">{r.dependencyVerified ? "Verified" : "Pending"}</td><td className="p-3">{r.malwareStatus}</td><td className="p-3">{r.certificateStatus}</td><td className="p-3 flex gap-2"><AdminActionButton url="/api/admin/supply-chain" method="POST" label="Sign" body={{ versionId: r.versionId, action: "SIGN" }} confirmText="Sign this exact release manifest?" /><AdminActionButton url="/api/admin/supply-chain" method="POST" label={r.malwareStatus === "PENDING_SCAN" ? "Scan" : "Rescan"} body={{ versionId: r.versionId, action: "RECORD_SCAN" }} confirmText="Scan the current private artifact bytes?" /></td></tr>)}</tbody></table></div></main>;
}
