import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../generated/prisma/client";

const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL! }) });
const catalog = [
  { slug:"bke-deskflow",name:"BKE DeskFlow",summary:"Focused desktop operations for small teams.",description:"A dependable desktop toolkit for structured workflows, local reporting, and secure exports.",type:"SOFTWARE" as const,policy:{name:"Single User",maxSeats:1,maxDevicesPerSeat:2,validityDays:null},price:{name:"Perpetual license",amountMinor:149900,billingType:"ONE_TIME" as const} },
  { slug:"bke-cloudops",name:"BKE CloudOps",summary:"Shared SaaS operations with annual access.",description:"A secure hosted workspace for teams that need visibility, accountability, and reliable operational records.",type:"SAAS" as const,policy:{name:"Professional",maxSeats:5,maxDevicesPerSeat:3,validityDays:365},price:{name:"Annual team plan",amountMinor:299900,billingType:"SUBSCRIPTION" as const,intervalUnit:"YEAR" as const,intervalCount:1} },
  { slug:"bke-institution-suite",name:"BKE Institution Suite",summary:"Flexible deployment for organizations and institutions.",description:"Organization licensing with authorized users, managed devices, and a central customer portal.",type:"HYBRID" as const,policy:{name:"Institution 25",maxSeats:25,maxDevicesPerSeat:2,validityDays:365},price:{name:"Annual organization license",amountMinor:1199900,billingType:"SUBSCRIPTION" as const,intervalUnit:"YEAR" as const,intervalCount:1} },
];
async function main(){for(const item of catalog){const product=await db.product.upsert({where:{slug:item.slug},update:{name:item.name,summary:item.summary,description:item.description,type:item.type,active:true},create:{slug:item.slug,name:item.name,summary:item.summary,description:item.description,type:item.type}});let policy=await db.licensePolicy.findFirst({where:{productId:product.id,name:item.policy.name}});policy??=await db.licensePolicy.create({data:{productId:product.id,...item.policy}});const exists=await db.price.findFirst({where:{productId:product.id,name:item.price.name}});if(!exists)await db.price.create({data:{productId:product.id,licensePolicyId:policy.id,currency:"PHP",active:true,...item.price}})}console.info(`Seeded ${catalog.length} BKE Digital Solutions products.`)}
main().finally(()=>db.$disconnect());
