import { NextResponse } from "next/server";
import { z } from "zod";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { requireAccountCapability } from "@/lib/authorization";
import { apiError } from "@/lib/http";
import { assertSameOrigin } from "@/lib/security/request";
import { inviteOrganizationMember, resendOrganizationInvitation, revokeOrganizationInvitation, expirePendingOrganizationInvitations } from "@/lib/organizations";
const schema = z.discriminatedUnion("action", [z.object({ action: z.literal("create"), email: z.string().email(), role: z.enum(["OWNER", "BILLING", "LICENSE_MANAGER", "MEMBER"]) }), z.object({ action: z.literal("resend"), invitationId: z.string().cuid() }), z.object({ action: z.literal("revoke"), invitationId: z.string().cuid() }), z.object({ action: z.literal("expire") })]);
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await requireUser(); const { id } = await params; await expirePendingOrganizationInvitations(); await requireAccountCapability(user.id, id, "MANAGE_MEMBERS"); return NextResponse.json(await db.invitation.findMany({ where: { accountId: id }, orderBy: { createdAt: "desc" }, select: { id: true, email: true, role: true, status: true, expiresAt: true, createdAt: true } })); } catch (error) { return apiError(error); } }
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) { try { assertSameOrigin(request); const user = await requireUser(); const { id } = await params; const input = schema.parse(await request.json()); await expirePendingOrganizationInvitations(); if (input.action === "create") { const result = await inviteOrganizationMember({ actorId: user.id, accountId: id, email: input.email, role: input.role }); return NextResponse.json({ id: result.invitation.id, token: result.token }, { status: 201 }); } if (input.action === "resend") { const result = await resendOrganizationInvitation({ actorId: user.id, invitationId: input.invitationId }); return NextResponse.json({ id: result.invitation.id, token: result.token }); } if (input.action === "revoke") return NextResponse.json(await revokeOrganizationInvitation({ actorId: user.id, invitationId: input.invitationId })); return NextResponse.json(await expirePendingOrganizationInvitations()); } catch (error) { return apiError(error); } }
