import "dotenv/config";
import { createHash, createHmac } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../../generated/prisma/client";

const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL! }) });
let userId="",accountId="",purchasePlanId="",orderId="",checkoutId="",licenseKey="",licenseId="",subscriptionId="";let paidRaw=Buffer.alloc(0);

describe.sequential("database-backed mock commerce lifecycle",()=>{
  beforeAll(async()=>{
    const plan=await db.purchasePlan.findFirstOrThrow({where:{edition:{product:{slug:"bke-cloudops"}},type:"ANNUAL",active:true}});purchasePlanId=plan.id;
    const cloudOps=await db.product.findUniqueOrThrow({where:{slug:"bke-cloudops"}});
    await db.productVersion.updateMany({where:{productId:cloudOps.id,version:"1.0.0"},data:{active:true,lifecycle:"STABLE",publishedAt:new Date(),isLatest:true}});
    const suffix=Date.now().toString(36);const user=await db.user.create({data:{email:`integration-${suffix}@bke.test`,name:"Integration Customer",emailVerified:new Date(),ownedAccounts:{create:{type:"INDIVIDUAL",displayName:"Integration Customer",billingEmail:`integration-${suffix}@bke.test`}}},include:{ownedAccounts:true}});userId=user.id;accountId=user.ownedAccounts[0]!.id;
  });
  afterAll(async()=>{await db.$disconnect()});
  it("server-reprices and creates a pending checkout",async()=>{const{createCheckout}=await import("@/lib/checkout");const result=await createCheckout(userId,purchasePlanId,accountId);orderId=result.orderId;const attempt=await db.paymentAttempt.findFirstOrThrow({where:{orderId}});checkoutId=attempt.externalCheckoutId!;expect(result.checkoutUrl).toContain("/checkout/mock");expect((await db.order.findUniqueOrThrow({where:{id:orderId}})).status).toBe("PENDING")});
  it("confirms payment, finalizes invoice, and issues one subscription license",async()=>{const order=await db.order.findUniqueOrThrow({where:{id:orderId}});const event={eventId:`evt_paid_${orderId}`,type:"payment.paid",externalPaymentId:`pay_${orderId}`,externalCheckoutId:checkoutId,reference:order.number,amountMinor:order.totalMinor,currency:order.currency,livemode:false,occurredAt:new Date().toISOString()};paidRaw=Buffer.from(JSON.stringify(event));const signature=createHmac("sha256",process.env.SESSION_SECRET!).update(paidRaw).digest("hex");const{processPaymentWebhook}=await import("@/lib/webhooks");await processPaymentWebhook(paidRaw,new Headers({"x-mock-signature":signature}));const paid=await db.order.findUniqueOrThrow({where:{id:orderId},include:{invoice:true,licenses:true,subscriptions:true,attempts:true}});expect(paid.status).toBe("PAID");expect(paid.invoice?.status).toBe("FINAL");expect(paid.attempts[0]?.status).toBe("COMPLETED");expect(paid.licenses).toHaveLength(1);expect(paid.subscriptions).toHaveLength(1);licenseId=paid.licenses[0]!.id;subscriptionId=paid.subscriptions[0]!.id;const{decryptLicenseKey}=await import("@/lib/security/crypto");licenseKey=decryptLicenseKey(paid.licenses[0]!.keyCiphertext!)});
  it("replays the exact same event without duplicate side effects",async()=>{const signature=createHmac("sha256",process.env.SESSION_SECRET!).update(paidRaw).digest("hex");const{processPaymentWebhook}=await import("@/lib/webhooks");for(let i=0;i<3;i++)expect(await processPaymentWebhook(paidRaw,new Headers({"x-mock-signature":signature}))).toEqual({duplicate:true});expect(await db.license.count({where:{orderId}})).toBe(1);expect(await db.payment.count({where:{orderId}})).toBe(1)});
  it("rejects a conflicting replay and preserves the original settlement",async()=>{const original=JSON.parse(paidRaw.toString("utf8"));const conflict=Buffer.from(JSON.stringify({...original,amountMinor:original.amountMinor+1}));const signature=createHmac("sha256",process.env.SESSION_SECRET!).update(conflict).digest("hex");const{processPaymentWebhook}=await import("@/lib/webhooks");await expect(processPaymentWebhook(conflict,new Headers({"x-mock-signature":signature}))).rejects.toThrow("PAYMENT_EVENT_REPLAY_CONFLICT");const row=await db.webhookEvent.findUniqueOrThrow({where:{provider_externalEventId:{provider:"mock",externalEventId:original.eventId}}});expect(row.conflictCount).toBe(1);expect(await db.license.count({where:{orderId}})).toBe(1)});
  it("does not duplicate entitlements or commerce email for an overlapping paid event",async()=>{const original=JSON.parse(paidRaw.toString("utf8"));const overlap=Buffer.from(JSON.stringify({...original,eventId:`evt_paid_overlap_${orderId}`}));const signature=createHmac("sha256",process.env.SESSION_SECRET!).update(overlap).digest("hex");const{processPaymentWebhook}=await import("@/lib/webhooks");expect(await processPaymentWebhook(overlap,new Headers({"x-mock-signature":signature}))).toEqual({processed:true});expect(await db.license.count({where:{orderId}})).toBe(1);expect(await db.emailOutbox.count({where:{deduplicationKey:{in:[`payment-receipt:${orderId}`,`invoice-issued:${orderId}`,`entitlement-issued:${orderId}`]}}})).toBe(3)});
  it("reconciles matching provider state and stores safe evidence",async()=>{const order=await db.order.findUniqueOrThrow({where:{id:orderId}});const provider={name:"mock",async createCheckout(){return{externalId:"unused",checkoutUrl:"http://localhost"}},async verifyAndParseWebhook(){throw new Error("unused")},async retrievePayment(externalId:string){return{externalId,status:"paid" as const,amountMinor:order.totalMinor,currency:order.currency,livemode:false}}};const{reconcileAndRecord}=await import("@/lib/reconciliation");const result=await reconcileAndRecord(orderId,userId,provider);expect(result).toMatchObject({classification:"MATCHED",status:"MATCHED"});expect(JSON.stringify(result)).not.toContain("secret")});
  it("enforces the device limit and rejects an invalid key",async()=>{const{POST}=await import("@/app/api/licenses/activate/route");const run=Date.now().toString(36);for(let i=0;i<15;i++){const response=await POST(new Request("http://localhost/api/licenses/activate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({licenseKey,operationId:`integration-${run}-activation-${i}`,installationId:`integration-installation-${run}-${i}`.padEnd(40,"x"),deviceId:`integration-device-${run}-${i}`.padEnd(20,"x")})}));expect(response.status).toBe(201)}const blocked=await POST(new Request("http://localhost/api/licenses/activate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({licenseKey,operationId:`integration-${run}-activation-over-limit`,installationId:`integration-installation-${run}-over-limit`.padEnd(40,"x"),deviceId:`integration-device-${run}-over-limit`})}));expect(blocked.status).toBe(409);const invalidKey=licenseKey.slice(0,-1)+(licenseKey.endsWith("0")?"1":"0");const forged=await POST(new Request("http://localhost/api/licenses/activate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({licenseKey:invalidKey,operationId:`integration-${run}-activation-forged`,installationId:"forged-installation-identifier".padEnd(40,"x"),deviceId:"forged-device-identifier"})}));expect(forged.status).toBe(400)});
  it("retries a previously failed webhook and records failure without issuing a license",async()=>{const{createCheckout}=await import("@/lib/checkout");const result=await createCheckout(userId,purchasePlanId,accountId);const order=await db.order.findUniqueOrThrow({where:{id:result.orderId},include:{attempts:true}});const payload={eventId:`evt_failed_${order.id}`,type:"payment.failed",externalPaymentId:`pay_failed_${order.id}`,externalCheckoutId:order.attempts[0]!.externalCheckoutId,reference:order.number,amountMinor:order.totalMinor,currency:order.currency,livemode:false,occurredAt:new Date().toISOString()};const raw=Buffer.from(JSON.stringify(payload));await db.webhookEvent.create({data:{provider:"mock",externalEventId:payload.eventId,eventType:payload.type,livemode:false,payloadHash:createHash("sha256").update(raw).digest("hex"),status:"FAILED",error:"TRANSIENT_TEST_FAILURE"}});const signature=createHmac("sha256",process.env.SESSION_SECRET!).update(raw).digest("hex");const{processPaymentWebhook}=await import("@/lib/webhooks");expect(await processPaymentWebhook(raw,new Headers({"x-mock-signature":signature}))).toEqual({processed:true});expect((await db.webhookEvent.findUniqueOrThrow({where:{provider_externalEventId:{provider:"mock",externalEventId:payload.eventId}}})).status).toBe("PROCESSED");expect((await db.payment.findFirstOrThrow({where:{orderId:order.id}})).status).toBe("FAILED");expect(await db.license.count({where:{orderId:order.id}})).toBe(0)});
  it("requests a full refund idempotently without changing access before a webhook",async()=>{const provider={name:"mock",async createCheckout(){return{externalId:"unused",checkoutUrl:"http://localhost"}},async verifyAndParseWebhook(){throw new Error("unused")},async createRefund(input:{paymentId:string;amountMinor:number}){return{externalId:`ref_${orderId}`,status:"pending" as const,amountMinor:input.amountMinor,paymentId:input.paymentId}}};const{requestFullRefund}=await import("@/lib/refunds");const first=await requestFullRefund({orderId,requestedById:userId,reason:"requested_by_customer"},provider);const second=await requestFullRefund({orderId,requestedById:userId,reason:"requested_by_customer"},provider);expect(second.id).toBe(first.id);expect((await db.order.findUniqueOrThrow({where:{id:orderId}})).status).toBe("PAID");expect(await db.refundOperation.count({where:{orderId}})).toBe(1)});
  it("expires subscriptions and licenses",async()=>{await db.subscription.update({where:{id:subscriptionId},data:{currentPeriodEnd:new Date(Date.now()-1000)}});await db.license.update({where:{id:licenseId},data:{expiresAt:new Date(Date.now()-1000)}});const{runScheduledJob}=await import("@/lib/scheduler/service");const result=await runScheduledJob({key:"entitlements.expiration",trigger:"MANUAL",idempotencyKey:`lifecycle-expiration-${licenseId}`});expect("error" in result).toBe(false);expect((await db.subscription.findUniqueOrThrow({where:{id:subscriptionId}})).status).toBe("EXPIRED");expect((await db.license.findUniqueOrThrow({where:{id:licenseId}})).status).toBe("EXPIRED")});
  it("processes a refund once and revokes the entitlement",async()=>{const order=await db.order.findUniqueOrThrow({where:{id:orderId}});const payload={eventId:`evt_refund_${order.id}`,type:"payment.refunded",externalPaymentId:`pay_${order.id}`,externalCheckoutId:checkoutId,externalRefundId:`ref_${order.id}`,reference:order.number,amountMinor:order.totalMinor,currency:order.currency,livemode:false,occurredAt:new Date().toISOString()};const raw=Buffer.from(JSON.stringify(payload));const signature=createHmac("sha256",process.env.SESSION_SECRET!).update(raw).digest("hex");const{processPaymentWebhook}=await import("@/lib/webhooks");await processPaymentWebhook(raw,new Headers({"x-mock-signature":signature}));for(let i=0;i<2;i++)expect(await processPaymentWebhook(raw,new Headers({"x-mock-signature":signature}))).toEqual({duplicate:true});expect((await db.order.findUniqueOrThrow({where:{id:orderId}})).status).toBe("REFUNDED");expect((await db.payment.findFirstOrThrow({where:{orderId}})).status).toBe("REFUNDED");expect((await db.refundOperation.findFirstOrThrow({where:{orderId}})).status).toBe("SUCCEEDED");expect((await db.license.findUniqueOrThrow({where:{id:licenseId}})).status).toBe("REVOKED");expect((await db.subscription.findUniqueOrThrow({where:{id:subscriptionId}})).status).toBe("CANCELLED")});
  it("keeps another customer outside the ownership boundary",async()=>{const outsider=await db.user.create({data:{email:`outsider-${Date.now()}@bke.test`,name:"Outsider",emailVerified:new Date()}});const visible=await db.order.findFirst({where:{id:orderId,account:{OR:[{ownerId:outsider.id},{memberships:{some:{userId:outsider.id}}}]}}});expect(visible).toBeNull()});
});
