import "dotenv/config";
import { createHmac } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../../generated/prisma/client";

const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL! }) });
let userId="",accountId="",priceId="",orderId="",checkoutId="",licenseKey="",licenseId="",subscriptionId="";

describe.sequential("database-backed mock commerce lifecycle",()=>{
  beforeAll(async()=>{
    const product=await db.product.findUniqueOrThrow({where:{slug:"bke-cloudops"},include:{prices:{where:{active:true},take:1}}});priceId=product.prices[0]!.id;
    const suffix=Date.now().toString(36);const user=await db.user.create({data:{email:`integration-${suffix}@bke.test`,name:"Integration Customer",emailVerified:new Date(),ownedAccounts:{create:{type:"INDIVIDUAL",displayName:"Integration Customer",billingEmail:`integration-${suffix}@bke.test`}}},include:{ownedAccounts:true}});userId=user.id;accountId=user.ownedAccounts[0]!.id;
  });
  afterAll(async()=>{await db.$disconnect()});
  it("server-reprices and creates a pending checkout",async()=>{const{createCheckout}=await import("@/lib/checkout");const result=await createCheckout(userId,accountId,[{priceId,quantity:1}]);orderId=result.orderId;const attempt=await db.paymentAttempt.findFirstOrThrow({where:{orderId}});checkoutId=attempt.externalCheckoutId!;expect(result.checkoutUrl).toContain("/checkout/mock");expect((await db.order.findUniqueOrThrow({where:{id:orderId}})).status).toBe("PENDING")});
  it("confirms payment, finalizes invoice, and issues one subscription license",async()=>{const order=await db.order.findUniqueOrThrow({where:{id:orderId}});const event={eventId:`evt_paid_${orderId}`,type:"payment.paid",externalPaymentId:`pay_${orderId}`,externalCheckoutId:checkoutId,reference:order.number,amountMinor:order.totalMinor,currency:order.currency,livemode:false,occurredAt:new Date().toISOString()};const raw=Buffer.from(JSON.stringify(event));const signature=createHmac("sha256",process.env.SESSION_SECRET!).update(raw).digest("hex");const{processPaymentWebhook}=await import("@/lib/webhooks");await processPaymentWebhook(raw,new Headers({"x-mock-signature":signature}));const paid=await db.order.findUniqueOrThrow({where:{id:orderId},include:{invoice:true,licenses:true,subscriptions:true}});expect(paid.status).toBe("PAID");expect(paid.invoice?.status).toBe("FINAL");expect(paid.licenses).toHaveLength(1);expect(paid.subscriptions).toHaveLength(1);licenseId=paid.licenses[0]!.id;subscriptionId=paid.subscriptions[0]!.id;const{decryptLicenseKey}=await import("@/lib/security/crypto");licenseKey=decryptLicenseKey(paid.licenses[0]!.keyCiphertext!)});
  it("replays the same event without duplicate side effects",async()=>{const event=await db.webhookEvent.findFirstOrThrow({where:{eventType:"payment.paid",externalEventId:`evt_paid_${orderId}`}});const order=await db.order.findUniqueOrThrow({where:{id:orderId}});const payload={eventId:event.externalEventId,type:"payment.paid",externalPaymentId:`pay_${orderId}`,externalCheckoutId:checkoutId,reference:order.number,amountMinor:order.totalMinor,currency:order.currency,livemode:false,occurredAt:new Date().toISOString()};const raw=Buffer.from(JSON.stringify(payload));const signature=createHmac("sha256",process.env.SESSION_SECRET!).update(raw).digest("hex");const{processPaymentWebhook}=await import("@/lib/webhooks");for(let i=0;i<3;i++)expect(await processPaymentWebhook(raw,new Headers({"x-mock-signature":signature}))).toEqual({duplicate:true});expect(await db.license.count({where:{orderId}})).toBe(1);expect(await db.payment.count({where:{orderId}})).toBe(1)});
  it("reconciles matching provider state without exposing provider data",async()=>{const order=await db.order.findUniqueOrThrow({where:{id:orderId}});const provider={name:"mock",async createCheckout(){return{externalId:"unused",checkoutUrl:"http://localhost"}},async verifyAndParseWebhook(){throw new Error("unused")},async retrievePayment(externalId:string){return{externalId,status:"paid" as const,amountMinor:order.totalMinor,currency:order.currency,livemode:false}}};const{reconcilePayment}=await import("@/lib/reconciliation");expect(await reconcilePayment(orderId,provider)).toMatchObject({matched:true,differences:[]})});
  it("enforces the device limit and rejects an invalid key",async()=>{const{POST}=await import("@/app/api/licenses/activate/route");for(let i=0;i<15;i++){const response=await POST(new Request("http://localhost/api/licenses/activate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({licenseKey,deviceId:`integration-device-${i}`.padEnd(20,"x")})}));expect(response.status).toBe(200)}const blocked=await POST(new Request("http://localhost/api/licenses/activate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({licenseKey,deviceId:"integration-device-over-limit"})}));expect(blocked.status).toBe(409);const forged=await POST(new Request("http://localhost/api/licenses/activate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({licenseKey:licenseKey.replace(/.$/,"0"),deviceId:"forged-device-identifier"})}));expect(forged.status).toBe(400)});
  it("records a failed payment without issuing a license",async()=>{const{createCheckout}=await import("@/lib/checkout");const result=await createCheckout(userId,accountId,[{priceId,quantity:1}]);const order=await db.order.findUniqueOrThrow({where:{id:result.orderId},include:{attempts:true}});const payload={eventId:`evt_failed_${order.id}`,type:"payment.failed",externalPaymentId:`pay_failed_${order.id}`,externalCheckoutId:order.attempts[0]!.externalCheckoutId,reference:order.number,amountMinor:order.totalMinor,currency:order.currency,livemode:false,occurredAt:new Date().toISOString()};const raw=Buffer.from(JSON.stringify(payload));const signature=createHmac("sha256",process.env.SESSION_SECRET!).update(raw).digest("hex");const{processPaymentWebhook}=await import("@/lib/webhooks");await processPaymentWebhook(raw,new Headers({"x-mock-signature":signature}));expect((await db.payment.findFirstOrThrow({where:{orderId:order.id}})).status).toBe("FAILED");expect(await db.license.count({where:{orderId:order.id}})).toBe(0)});
  it("expires subscriptions and licenses",async()=>{await db.subscription.update({where:{id:subscriptionId},data:{currentPeriodEnd:new Date(Date.now()-1000)}});await db.license.update({where:{id:licenseId},data:{expiresAt:new Date(Date.now()-1000)}});const{POST}=await import("@/app/api/cron/expirations/route");const response=await POST(new Request("http://localhost/api/cron/expirations",{method:"POST",headers:{authorization:`Bearer ${process.env.CRON_SECRET}`}}));expect(response.status).toBe(200);expect((await db.subscription.findUniqueOrThrow({where:{id:subscriptionId}})).status).toBe("EXPIRED");expect((await db.license.findUniqueOrThrow({where:{id:licenseId}})).status).toBe("EXPIRED")});
  it("processes a refund once and revokes the entitlement",async()=>{const order=await db.order.findUniqueOrThrow({where:{id:orderId}});const payload={eventId:`evt_refund_${order.id}`,type:"payment.refunded",externalPaymentId:`pay_${order.id}`,externalCheckoutId:checkoutId,reference:order.number,amountMinor:order.totalMinor,currency:order.currency,livemode:false,occurredAt:new Date().toISOString()};const raw=Buffer.from(JSON.stringify(payload));const signature=createHmac("sha256",process.env.SESSION_SECRET!).update(raw).digest("hex");const{processPaymentWebhook}=await import("@/lib/webhooks");await processPaymentWebhook(raw,new Headers({"x-mock-signature":signature}));for(let i=0;i<2;i++)expect(await processPaymentWebhook(raw,new Headers({"x-mock-signature":signature}))).toEqual({duplicate:true});expect((await db.order.findUniqueOrThrow({where:{id:orderId}})).status).toBe("REFUNDED");expect((await db.payment.findFirstOrThrow({where:{orderId}})).status).toBe("REFUNDED");expect((await db.license.findUniqueOrThrow({where:{id:licenseId}})).status).toBe("REVOKED");expect((await db.subscription.findUniqueOrThrow({where:{id:subscriptionId}})).status).toBe("CANCELLED")});
  it("keeps another customer outside the ownership boundary",async()=>{const outsider=await db.user.create({data:{email:`outsider-${Date.now()}@bke.test`,name:"Outsider",emailVerified:new Date()}});const visible=await db.order.findFirst({where:{id:orderId,account:{OR:[{ownerId:outsider.id},{memberships:{some:{userId:outsider.id}}}]}}});expect(visible).toBeNull()});
});
