import "dotenv/config";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../../generated/prisma/client";
import { changeTrial, grantProductTrial } from "@/lib/trials";

const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL!})});
let userId="",adminId="",accountId="",editionId="",trialId="",licenseId="";
describe.sequential("product trial lifecycle",()=>{
  beforeAll(async()=>{const suffix=Date.now().toString(36);const user=await db.user.create({data:{email:`trial-${suffix}@bke.test`,emailVerified:new Date(),ownedAccounts:{create:{type:"INDIVIDUAL",displayName:"Trial Customer",billingEmail:`trial-${suffix}@bke.test`}}},include:{ownedAccounts:true}});userId=user.id;accountId=user.ownedAccounts[0]!.id;adminId=(await db.user.create({data:{email:`trial-admin-${suffix}@bke.test`,emailVerified:new Date(),role:"ADMIN"}})).id;editionId=(await db.edition.findFirstOrThrow({where:{product:{slug:"bke-deskflow"},active:true}})).id});
  afterAll(()=>db.$disconnect());
  it("issues one seven-day self-service product entitlement",async()=>{const trial=await grantProductTrial({accountId,editionId,source:"SELF_SERVICE",actorId:userId});trialId=trial.id;licenseId=trial.licenseId;expect(trial.selfServiceYear).toBe(new Date().getUTCFullYear());expect(trial.trialEndsAt.getTime()-trial.trialStartsAt.getTime()).toBe(7*86400000);expect(trial.graceEndsAt).toEqual(trial.trialEndsAt);const license=await db.license.findUniqueOrThrow({where:{id:licenseId},include:{order:true}});expect(license.status).toBe("ACTIVE");expect(license.order.totalMinor).toBe(0);expect(license.expiresAt).toEqual(trial.graceEndsAt)});
  it("rejects another edition of the same product in the same account and year",async()=>{const original=await db.edition.findUniqueOrThrow({where:{id:editionId}});const alternate=await db.edition.create({data:{productId:original.productId,slug:`trial-alt-${Date.now().toString(36)}`,name:"Trial alternate",maxUsers:1,maxDevicesPerUser:1}});try{await expect(grantProductTrial({accountId,editionId:alternate.id,source:"SELF_SERVICE",actorId:userId})).rejects.toThrow("TRIAL_ALREADY_USED_THIS_YEAR");expect(await db.trialGrant.count({where:{accountId,productId:original.productId,selfServiceYear:new Date().getUTCFullYear()}})).toBe(1)}finally{await db.edition.delete({where:{id:alternate.id}})}});
  it("issues exactly one entitlement under concurrent self-service requests",async()=>{const suffix=Date.now().toString(36);const concurrent=await db.user.create({data:{email:`trial-concurrent-${suffix}@bke.test`,emailVerified:new Date(),ownedAccounts:{create:{type:"INDIVIDUAL",displayName:"Concurrent Trial",billingEmail:`trial-concurrent-${suffix}@bke.test`}}},include:{ownedAccounts:true}});const concurrentAccountId=concurrent.ownedAccounts[0]!.id;const results=await Promise.allSettled([grantProductTrial({accountId:concurrentAccountId,editionId,source:"SELF_SERVICE",actorId:concurrent.id}),grantProductTrial({accountId:concurrentAccountId,editionId,source:"SELF_SERVICE",actorId:concurrent.id})]);expect(results.filter(result=>result.status==="fulfilled")).toHaveLength(1);expect(await db.trialGrant.count({where:{accountId:concurrentAccountId,product:{slug:"bke-deskflow"},selfServiceYear:new Date().getUTCFullYear()}})).toBe(1);expect(await db.license.count({where:{accountId:concurrentAccountId,product:{slug:"bke-deskflow"}}})).toBe(1)});
  it("allows an administrator to grant an extra trial with grace",async()=>{const trial=await grantProductTrial({accountId,editionId,source:"ADMIN",actorId:adminId,graceDays:3});expect(trial.selfServiceYear).toBeNull();expect(trial.graceEndsAt.getTime()-trial.trialEndsAt.getTime()).toBe(3*86400000);expect(await db.auditLog.count({where:{targetId:trial.id,action:"TRIAL_GRANTED_BY_ADMIN"}})).toBe(1)});
  it("changes grace and revokes access transactionally",async()=>{const changed=await changeTrial({trialId,actorId:adminId,action:"SET_GRACE",graceDays:5});expect(changed.graceEndsAt.getTime()-changed.trialEndsAt.getTime()).toBe(5*86400000);expect((await db.license.findUniqueOrThrow({where:{id:licenseId}})).expiresAt).toEqual(changed.graceEndsAt);await changeTrial({trialId,actorId:adminId,action:"REVOKE"});expect((await db.license.findUniqueOrThrow({where:{id:licenseId}})).status).toBe("REVOKED");expect((await db.trialGrant.findUniqueOrThrow({where:{id:trialId}})).revokedAt).not.toBeNull()});
});
