import Link from "next/link";
import { db } from "@/lib/db";

export default async function Home() {
  const products = await db.product.findMany({ where: { active: true }, include: { prices: { where: { active: true }, take: 1 } }, take: 3 });
  return <>
    <section className="overflow-hidden bg-[#092f47] py-24 text-white"><div className="shell grid gap-12 md:grid-cols-[1.2fr_.8fr] md:items-center"><div><p className="mb-4 font-bold uppercase tracking-[.22em] text-[#42d4c8]">Built for dependable work</p><h1 className="max-w-3xl text-5xl font-black leading-tight md:text-7xl">Software that moves your organization forward.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-200">Secure products, flexible licenses, and practical SaaS solutions for individuals, businesses, and institutions.</p><div className="mt-9 flex gap-3"><Link className="button bg-[#42d4c8]! text-[#092f47]!" href="/products">Explore products</Link><Link className="button secondary" href="/licensing">How licensing works</Link></div></div><div className="card rotate-2 bg-white/10 p-8 text-white backdrop-blur"><p className="text-sm uppercase tracking-widest text-cyan-200">One secure portal</p><div className="mt-8 grid gap-4">{["Manage users and devices", "Review orders and invoices", "Renew licenses on your terms"].map((x, i)=><div key={x} className="rounded-xl bg-white/10 p-5"><span className="mr-3 text-cyan-300">0{i+1}</span>{x}</div>)}</div></div></div></section>
    <section className="shell py-20"><div className="flex items-end justify-between"><div><p className="font-bold text-[#0b7197]">Our solutions</p><h2 className="mt-2 text-4xl font-black">Choose what fits today.</h2></div><Link href="/products" className="font-bold text-[#0b7197]">View catalog →</Link></div><div className="mt-10 grid gap-6 md:grid-cols-3">{products.map(p=><Link href={`/products/${p.slug}`} key={p.id} className="card p-7 transition hover:-translate-y-1"><p className="text-xs font-bold uppercase tracking-widest text-[#0b7197]">{p.type}</p><h3 className="mt-3 text-2xl font-black">{p.name}</h3><p className="mt-3 leading-7 text-slate-600">{p.summary}</p><p className="mt-7 font-bold">{p.prices[0] ? `From ₱${(p.prices[0].amountMinor/100).toLocaleString("en-PH")}` : "Contact us"}</p></Link>)}</div></section>
  </>;
}
