import { NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db";
import { requireAdmin, requireRecentAdmin } from "@/lib/auth";
import { apiError } from "@/lib/http";
import { assertSameOrigin, clientIp } from "@/lib/security/request";
import { rateLimit } from "@/lib/security/rate-limit";
import { env } from "@/lib/env";
import { createPublicKey, verify } from "node:crypto";
import { scanArtifact } from "@/lib/supply-chain/scanner";
const schema = z.object({ versionId: z.string().min(1), action: z.enum(["RECORD_SCAN", "VERIFY_SIGNATURE"]).optional(), signature: z.string().min(16).optional() });
function publicKey() { if (!env.SUPPLY_CHAIN_SIGNING_PUBLIC_KEY) throw new Error("SUPPLY_CHAIN_TRUST_KEY_NOT_CONFIGURED"); const raw = env.SUPPLY_CHAIN_SIGNING_PUBLIC_KEY.includes("BEGIN") ? env.SUPPLY_CHAIN_SIGNING_PUBLIC_KEY : Buffer.from(env.SUPPLY_CHAIN_SIGNING_PUBLIC_KEY, "base64").toString("utf8"); return createPublicKey(raw); }
export async function GET() { try { await requireAdmin(); return NextResponse.json(await db.supplyChainEvidence.findMany({ include: { verificationEvidence: true, version: { include: { product: { select: { name: true } }, artifacts: { select: { name: true, sha256: true, sizeBytes: true } } } } }, orderBy: { builtAt: "desc" } })); } catch (e) { return apiError(e); } }
export async function POST(request: Request) { try { assertSameOrigin(request); const admin = await requireRecentAdmin(); const limited = await rateLimit(`admin-supply-chain:${admin.id}:${clientIp(request)}`, 30, 3600); if (!limited.allowed) throw new Error("RATE_LIMITED"); const input = schema.parse(await request.json()); const existing = await db.supplyChainEvidence.findUnique({ where: { versionId: input.versionId }, include: { version: { include: { artifacts: true } } } }); if (!existing) throw new Error("NOT_FOUND"); const artifactHash = existing.version.artifacts.map((a) => `${a.id}:${a.sha256}`).sort().join("|"); if (input.action === "VERIFY_SIGNATURE") { if (!input.signature) throw new Error("SIGNATURE_REQUIRED"); const valid = verify(null, Buffer.from(artifactHash), publicKey(), Buffer.from(input.signature, "base64")); await db.supplyChainVerificationEvidence.create({ data: { evidenceId: existing.id, kind: "SIGNATURE", artifactHash, signerKeyId: env.SUPPLY_CHAIN_SIGNING_KEY_ID, result: valid ? "VERIFIED" : "FAILED", failureReason: valid ? undefined : "SIGNATURE_MISMATCH", metadata: { algorithm: "Ed25519" } } }); if (!valid) throw new Error("SIGNATURE_INVALID"); await db.supplyChainEvidence.update({ where: { id: existing.id }, data: { signatureVerified: true, manifestSignature: input.signature } }); }
    if (input.action === "RECORD_SCAN") { const scan = await scanArtifact(artifactHash); await db.supplyChainVerificationEvidence.create({ data: { evidenceId: existing.id, kind: "MALWARE_SCAN", artifactHash, scannerId: scan.scannerId, scannerVersion: scan.scannerVersion, result: scan.result, reference: scan.reference, failureReason: scan.failureReason } }); await db.supplyChainEvidence.update({ where: { id: existing.id }, data: { malwareStatus: scan.result } }); if (scan.result !== "CLEAN") throw new Error("MALWARE_SCAN_NOT_CLEAN"); }
    await db.auditLog.create({ data: { actorId: admin.id, action: "SUPPLY_CHAIN_EVIDENCE_UPDATED", targetType: "SupplyChainEvidence", targetId: existing.id, metadata: { action: input.action } } }); return NextResponse.json({ ok: true }); } catch (e) { return apiError(e); } }
