"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { AdminEditionEditor, editionBody } from "@/components/admin-edition-editor";
import { AdminProductDelete } from "@/components/admin-product-delete";
import { AdminProductEditor } from "@/components/admin-product-editor";
import { AdminNewEdition } from "@/components/admin-new-edition";

type Plan={id:string;type:"PERPETUAL"|"MONTHLY"|"ANNUAL";amountMinor:number|null;annualDiscountBps:number|null;active:boolean};
type Edition={id:string;name:string;slug:string;description:string|null;features:unknown;maxUsers:number;maxDevicesPerUser:number;updatePolicy:"LIFETIME"|"ACTIVE_TERM"|"MAJOR_VERSION";active:boolean;purchasePlans:Plan[]};
type Product={id:string;productId:string|null;minimumAcceptedVersion:string|null;maximumAcceptedVersion:string|null;name:string;slug:string;summary:string;description:string;category:string;licenseType:string;featured:boolean;tags:string[];active:boolean;archivedAt:string|null;editions:Edition[];versions:{id:string;version:string;externalUrl:string|null;active:boolean;isLatest:boolean}[]};

export function AdminProductManager({products}:{products:Product[]}){const router=useRouter();const[error,setError]=useState("");
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=event.currentTarget;const fields=new FormData(form);const response=await fetch("/api/admin/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({productId:fields.get("productId"),slug:fields.get("slug"),name:fields.get("name"),summary:fields.get("summary"),description:fields.get("description"),minimumAcceptedVersion:fields.get("minimumAcceptedVersion")||null,maximumAcceptedVersion:fields.get("maximumAcceptedVersion")||null,category:fields.get("category"),licenseType:fields.get("licenseType"),tags:String(fields.get("tags")??"").split(",").map(value=>value.trim()).filter(Boolean),featured:fields.get("featured")==="on",type:"SOFTWARE",edition:editionBody(fields)})});if(!response.ok){const payload=await response.json();setError(payload.error??"Unable to create product");return}form.reset();router.refresh()}
  async function action(id:string,actionName:string){const response=await fetch(`/api/admin/products/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:actionName})});if(!response.ok)setError("Product update failed");router.refresh()}
  async function createVersion(event:FormEvent<HTMLFormElement>,id:string){event.preventDefault();setError("");const form=event.currentTarget;const fields=new FormData(form);const response=await fetch(`/api/admin/products/${id}/versions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({version:fields.get("version"),minimumVersion:fields.get("minimumVersion"),maximumVersion:fields.get("maximumVersion"),externalUrl:fields.get("externalUrl"),releaseNotes:fields.get("releaseNotes")})});if(!response.ok){setError((await response.json()).error??"Unable to create version");return}form.reset();router.refresh()}
  return <div className="grid gap-8"><form onSubmit={create} className="card grid gap-4 p-6 md:grid-cols-2"><h2 className="text-2xl font-black md:col-span-2">Create product and first edition</h2><Field name="name" label="Name"/><Field name="slug" label="Slug" pattern="[a-z0-9-]+"/><Field name="category" label="Category" defaultValue="General"/><Field name="licenseType" label="License type" defaultValue="Commercial"/><Field name="tags" label="Tags (comma separated)" wide optional/><Field name="summary" label="Short description" wide/><label className="label md:col-span-2">Long description<textarea className="input min-h-28" name="description" minLength={10} required/></label><h3 className="text-xl font-black md:col-span-2">Edition capabilities</h3><Field name="editionName" label="Edition name" defaultValue="Professional"/><Field name="editionSlug" label="Edition slug" defaultValue="professional" pattern="[a-z0-9-]+"/><Field name="editionDescription" label="Edition description" defaultValue="Professional edition"/><Field name="features" label="Features (comma separated)" defaultValue="Core features"/><Field name="maxUsers" label="Authorized users" type="number" defaultValue="1"/><Field name="maxDevices" label="Devices per user" type="number" defaultValue="1"/><label className="label">Update policy<select className="input" name="updatePolicy"><option value="LIFETIME">Lifetime updates</option><option value="ACTIVE_TERM">While subscription is active</option><option value="MAJOR_VERSION">Current major version</option></select></label><label className="flex items-center gap-2"><input type="checkbox" name="editionActive" defaultChecked/> Edition visible</label><h3 className="text-xl font-black md:col-span-2">Purchase plans</h3><label className="flex items-center gap-2"><input type="checkbox" name="perpetualEnabled" defaultChecked/> Perpetual</label><Field name="perpetualPrice" label="Perpetual price (PHP)" type="number" defaultValue="9999"/><label className="flex items-center gap-2"><input type="checkbox" name="monthlyEnabled" defaultChecked/> Monthly</label><Field name="monthlyPrice" label="Monthly price (PHP)" type="number" defaultValue="499"/><label className="flex items-center gap-2"><input type="checkbox" name="annualEnabled" defaultChecked/> Annual (derived from monthly)</label><Field name="annualDiscount" label="Annual discount (0–10%)" type="number" defaultValue="10"/><label className="flex items-center gap-2"><input type="checkbox" name="featured"/> Featured product</label>{error&&<p role="alert" className="text-red-700 md:col-span-2">{error}</p>}<button className="button md:col-span-2">Create draft product</button></form>
  {products.map(product=><section className="card p-6" key={product.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase text-[#3D75A7]">{product.active?"Published":product.archivedAt?"Archived":"Draft"}{product.featured?" · Featured":""}</p><h2 className="text-2xl font-black">{product.name}</h2><p className="text-sm text-slate-600">/{product.slug} · {product.category} · {product.editions.length} edition(s)</p></div><div className="flex flex-wrap gap-2">{product.archivedAt?<><button type="button" className="button secondary" onClick={()=>action(product.id,"RESTORE")}>Restore</button><AdminProductDelete productId={product.id} productName={product.name}/></>:<><button type="button" className="button secondary" onClick={()=>action(product.id,product.active?"UNPUBLISH":"PUBLISH")}>{product.active?"Unpublish":"Publish"}</button><button type="button" className="button secondary" onClick={()=>action(product.id,"ARCHIVE")}>Archive</button></>}</div></div><AdminProductEditor product={product}/><div className="mt-5"><h3 className="text-lg font-black">Editions and purchase plans</h3>{product.editions.map(edition=><AdminEditionEditor key={edition.id} edition={edition}/>)}</div><AdminNewEdition productId={product.id}/><div className="mt-5 grid gap-2">{product.versions.map(version=><p className="rounded-lg bg-slate-800 p-3 text-sm text-slate-100" key={version.id}>{version.version} · {version.externalUrl ?? "No external URL"} · {version.active?"Published":"Draft"}{version.isLatest?" · Latest":""}</p>)}</div><form onSubmit={event=>createVersion(event,product.id)} className="mt-5 grid gap-3 border-t pt-5 md:grid-cols-2"><h3 className="text-lg font-black md:col-span-2">Register software version</h3><Field name="version" label="Version"/><Field name="externalUrl" label="External URL" type="url"/><Field name="minimumVersion" label="Minimum accepted version" optional/><Field name="maximumVersion" label="Maximum accepted version" optional/><label className="label md:col-span-2">Release notes<textarea className="input" name="releaseNotes"/></label><button className="button md:col-span-2">Save and publish version</button></form></section>)}</div>}
function Field({name,label,type="text",wide=false,pattern,defaultValue,optional=false}:{name:string;label:string;type?:string;wide?:boolean;pattern?:string;defaultValue?:string;optional?:boolean}){const field=<label className={`label ${wide?"md:col-span-2":""}`}>{label}<input className="input" name={name} type={type} pattern={pattern} defaultValue={defaultValue} min={type==="number"?"0":undefined} step={type==="number"?"0.01":undefined} minLength={type==="text"&&!optional?2:undefined} required={!optional}/></label>;return name==="slug"?<>{field}<label className="label">Product ID<input className="input" name="productId" pattern="[a-z][a-z0-9-]*" required/></label></>:field}
