"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { AdminProductImageUpload } from "@/components/admin-product-image-upload";

type Product={id:string;productId:string|null;minimumAcceptedVersion:string|null;maximumAcceptedVersion:string|null;name:string;slug:string;summary:string;description:string;category:string;licenseType:string;featured:boolean;tags:string[]};
export function AdminProductEditor({product}:{product:Product}){
  const router=useRouter(); const[open,setOpen]=useState(false); const[error,setError]=useState("");
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget);const response=await fetch(`/api/admin/products/${product.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({productId:fields.get("productId"),minimumAcceptedVersion:fields.get("minimumAcceptedVersion")||undefined,maximumAcceptedVersion:fields.get("maximumAcceptedVersion")||undefined,name:fields.get("name"),slug:fields.get("slug"),summary:fields.get("summary"),description:fields.get("description"),category:fields.get("category"),licenseType:fields.get("licenseType"),featured:fields.get("featured")==="on",tags:String(fields.get("tags")??"").split(",").map(value=>value.trim()).filter(Boolean)})});if(!response.ok){setError((await response.json()).error??"Unable to save changes");return}setOpen(false);router.refresh()}
  return <div className="mt-4"><button className="text-sm font-bold text-[#3D75A7]" onClick={()=>setOpen(!open)}>{open?"Close editor":"Edit product"}</button>{open&&<div className="mt-4 rounded-xl border p-4"><form onSubmit={save} className="grid gap-3 md:grid-cols-2"><h3 className="font-black md:col-span-2">Licensing Policy</h3><label className="label">Product ID<input className="input" name="productId" defaultValue={product.productId??""} pattern="[a-z][a-z0-9-]*" required/></label><label className="label">Minimum accepted version<input className="input" name="minimumAcceptedVersion" defaultValue={product.minimumAcceptedVersion??""}/></label><label className="label">Maximum accepted version<input className="input" name="maximumAcceptedVersion" defaultValue={product.maximumAcceptedVersion??""}/></label><Field name="name" label="Name" value={product.name}/><Field name="slug" label="Slug" value={product.slug}/><Field name="category" label="Category" value={product.category}/><Field name="licenseType" label="License type" value={product.licenseType}/><Field name="summary" label="Short description" value={product.summary}/><label className="label md:col-span-2">Description<textarea className="input" name="description" defaultValue={product.description} required/></label><Field name="tags" label="Tags (comma separated)" value={product.tags.join(", ")}/><label className="flex items-center gap-2"><input name="featured" type="checkbox" defaultChecked={product.featured}/> Featured product</label>{error&&<p className="text-red-700">{error}</p>}<button className="button md:col-span-2">Save product metadata</button></form><AdminProductImageUpload productId={product.id}/></div>}</div>
}
function Field({name,label,value}:{name:string;label:string;value:string}){return <label className="label">{label}<input className="input" name={name} defaultValue={value} required/></label>}
