"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export function MfaEnrollmentForm() {
  const router = useRouter(); const [sent,setSent]=useState(false); const [codes,setCodes]=useState<string[]|null>(null); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function begin(){setBusy(true);setError("");const response=await fetch("/api/auth/mfa/enroll",{method:"POST"});const body=await response.json();setBusy(false);if(!response.ok)return setError(body.error==="RECENT_AUTH_REQUIRED"?"Sign in again before starting email verification.":body.error==="RATE_LIMITED"?"Please wait before requesting another code.":"Unable to start administrator verification.");setSent(true);if(body.emailSent===false)setError("Email delivery failed. Request a new code after checking the configured email provider.")}
  async function verify(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);const response=await fetch("/api/auth/mfa/enroll/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:form.get("code")})});const body=await response.json();setBusy(false);if(!response.ok)return setError("The code is invalid, expired, or has already been used.");setCodes(body.recoveryCodes)}
  if(codes)return <div className="card p-8"><h2 className="text-2xl font-bold">Save your recovery codes now</h2><p className="my-3">Each code works once. They will not be displayed again.</p><pre className="overflow-auto rounded bg-slate-950 p-4 text-white">{codes.join("\n")}</pre><button className="button mt-5" onClick={()=>{router.replace("/admin/security");router.refresh()}}>I saved these codes</button></div>;
  return <div className="card grid gap-5 p-8"><p>Administrator verification codes are sent to the verified email address on this account.</p>{!sent?<button className="button" disabled={busy} onClick={begin}>{busy?"Sending…":"Email my verification code"}</button>:<><p role="status" className="rounded-lg bg-green-50 p-3 text-sm text-green-800">A six-digit code was sent. It expires in 10 minutes.</p><form className="grid gap-4" onSubmit={verify}><label className="label">Email verification code<input className="input" name="code" required pattern="[0-9]{6}" inputMode="numeric" autoComplete="one-time-code"/></label><button className="button" disabled={busy}>{busy?"Verifying…":"Enable email verification"}</button></form><button className="button-secondary" disabled={busy} onClick={begin}>Email a new code</button></>}{error&&<p role="alert" className="text-red-700">{error}</p>}</div>;
}
