"use client";
import { useRef, useState } from "react";

export function SubscriptionRenewButton({ subscriptionId, documents }: { subscriptionId: string; documents: { versionId: string; title: string; slug: string }[] }) {
  const [open,setOpen]=useState(false); const [accepted,setAccepted]=useState<string[]>([]); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const panel=useRef<HTMLDivElement>(null);
  const available=documents.length===3;
  async function renew(){if(accepted.length!==documents.length){setError("Please review and accept each required document before continuing.");panel.current?.focus();return}setBusy(true);setError("");const response=await fetch(`/api/subscriptions/${subscriptionId}/renew`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({legalVersionIds:accepted})});const body=await response.json();if(!response.ok){setError(body.error??"Renewal checkout failed");setBusy(false);return}window.location.assign(body.checkoutUrl)}
  return <div className="mt-3">{!available?<p className="text-sm text-red-700">Renewal is temporarily unavailable because the required legal documents are not published.</p>:!open?<button className="button-secondary" onClick={()=>setOpen(true)}>Renew subscription</button>:<div ref={panel} tabIndex={-1} className="legal-consent-panel grid gap-3 outline-none" data-invalid={Boolean(error)||undefined}><div><h3 className="font-black">Review and accept before continuing</h3><p className={`text-sm ${error?"font-semibold text-red-700":"text-slate-600"}`}>{error||"Open and read each document before starting renewal."}</p></div>{documents.map(document=><label className="flex gap-2" key={document.versionId}><input className="mt-1 size-4" type="checkbox" checked={accepted.includes(document.versionId)} onChange={event=>{setAccepted(items=>event.target.checked?[...items,document.versionId]:items.filter(id=>id!==document.versionId));setError("")}}/><span>I have read and agree to the <a className="font-bold underline" href={`/legal/${document.slug}`} target="_blank" rel="noreferrer">{document.title}</a>.</span></label>)}<button className="button" disabled={busy} data-incomplete={accepted.length!==documents.length||undefined} onClick={renew}>{busy?"Starting…":"Continue renewal"}</button></div>}</div>;
}
