import type { ScheduledJob } from "@/v2/platform/scheduler/contracts";

export type SchedulerJobDefinitionMetadata = Omit<ScheduledJob, "handler">;

export const schedulerJobDefinitions = [
  { key: "storage.lifecycle", name: "Storage cleanup and deletion", description: "Recovers and processes private-storage cleanup, abandoned uploads, and completed product deletion.", category: "STORAGE", cadenceSeconds: 300, timeoutSeconds: 240, lockSeconds: 300, maxAttempts: 5, dryRunSupported: true, healthThresholdSeconds: 1800, auditPolicy: "FAILURES" },
  { key: "email.outbox", name: "Transactional email outbox", description: "Delivers pending mail, retries transient failures, and marks terminal failures.", category: "EMAIL", cadenceSeconds: 60, timeoutSeconds: 50, lockSeconds: 60, maxAttempts: 5, dryRunSupported: true, healthThresholdSeconds: 300, auditPolicy: "FAILURES" },
  { key: "subscriptions.renewal-reminders", name: "Subscription renewal reminders", description: "Queues deduplicated 14, 7, and 1 day customer-authorized renewal reminders.", category: "ENTITLEMENTS", cadenceSeconds: 3600, timeoutSeconds: 300, lockSeconds: 360, maxAttempts: 4, dryRunSupported: true, healthThresholdSeconds: 10800, auditPolicy: "FAILURES" },
  { key: "entitlements.expiration", name: "Entitlement expiration", description: "Synchronizes subscription, license, trial, grace-period, and download-grant expiration state.", category: "ENTITLEMENTS", cadenceSeconds: 300, timeoutSeconds: 240, lockSeconds: 300, maxAttempts: 5, dryRunSupported: true, healthThresholdSeconds: 1800, auditPolicy: "FAILURES" },
  { key: "commerce.lifecycle", name: "Commerce lifecycle", description: "Expires abandoned orders and attempts and releases stale offer reservations without settling payments.", category: "COMMERCE", cadenceSeconds: 900, timeoutSeconds: 120, lockSeconds: 180, maxAttempts: 4, dryRunSupported: true, healthThresholdSeconds: 3600, auditPolicy: "FAILURES" },
  { key: "customers.retention-review", name: "Customer retention review", description: "Calculates retention, privacy, purge-eligibility, and legal-hold review backlogs without automatic purge.", category: "CUSTOMER", cadenceSeconds: 86400, timeoutSeconds: 300, lockSeconds: 360, maxAttempts: 3, dryRunSupported: true, healthThresholdSeconds: 172800, auditPolicy: "FAILURES" },
  { key: "security.expired-records", name: "Expired authentication records", description: "Removes expired sessions, MFA challenges, verification, magic-link, and password-reset tokens.", category: "SECURITY", cadenceSeconds: 3600, timeoutSeconds: 120, lockSeconds: 180, maxAttempts: 4, dryRunSupported: true, healthThresholdSeconds: 10800, auditPolicy: "FAILURES" },
  { key: "payments.operations", name: "Payment operations", description: "Retries retryable stored webhooks and reports reconciliation candidates; never auto-settles or refunds.", category: "PAYMENTS", cadenceSeconds: 900, timeoutSeconds: 300, lockSeconds: 360, maxAttempts: 5, dryRunSupported: true, healthThresholdSeconds: 3600, auditPolicy: "ALL" },
  { key: "renewals.prepared-recovery", name: "Prepared renewal recovery", description: "Retries prepared successor lease issuance without extending entitlements twice.", category: "ENTITLEMENTS", cadenceSeconds: 300, timeoutSeconds: 240, lockSeconds: 300, maxAttempts: 5, dryRunSupported: true, healthThresholdSeconds: 1800, auditPolicy: "ALL" },
  { key: "backups.daily", name: "Encrypted daily backup", description: "Queues one encrypted PostgreSQL and private-object archive per UTC retention window.", category: "BACKUP", cadenceSeconds: 86400, timeoutSeconds: 120, lockSeconds: 180, maxAttempts: 3, dryRunSupported: true, healthThresholdSeconds: 172800, auditPolicy: "ALL" },
  { key: "backups.retention", name: "Backup retention", description: "Marks expired archives and queues deletion without touching current recovery points.", category: "BACKUP", cadenceSeconds: 86400, timeoutSeconds: 120, lockSeconds: 180, maxAttempts: 3, dryRunSupported: true, healthThresholdSeconds: 172800, auditPolicy: "ALL" },
] as const satisfies readonly SchedulerJobDefinitionMetadata[];
