import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { createSession, verifyPassword } from "@/lib/auth";
import { ADMIN_EMAIL_CHALLENGE_COOKIE, ADMIN_EMAIL_CHALLENGE_COOKIE_OPTIONS, createEmailChallenge } from "@/lib/admin-mfa";
import { loginSchema } from "@/v2/apps/web/http/validation";
import { assertSameOrigin, clientIp } from "@/v2/apps/web/http/request";
import { rateLimit } from "@/v2/apps/web/http/rate-limit";
import { securityEvent } from "@/v2/apps/web/security/events";
import { apiError } from "@/v2/apps/web/http/api-error";
import { pendingReacceptance } from "@/lib/legal/service";
export async function POST(request:Request){try{assertSameOrigin(request);const input=loginSchema.parse(await request.json());const user=await db.user.findUnique({where:{email:input.email},include:{credential:true,administratorMfa:true}});if(!(await rateLimit(`login:${clientIp(request)}:${input.email}`,8,900)).allowed){if(user?.role==="ADMIN")await securityEvent("SECURITY_RATE_LIMIT_TRIGGERED",request,user.id,{reason:"login"});return NextResponse.json({error:"RATE_LIMITED"},{status:429})}const valid=user?.credential?await verifyPassword(user.credential.passwordHash,input.password):false;if(!user||!valid){if(user?.role==="ADMIN")await securityEvent("ADMIN_PASSWORD_REJECTED",request,user.id);return NextResponse.json({error:"INVALID_CREDENTIALS"},{status:401})}if(user.role==="ADMIN"){await securityEvent("ADMIN_PASSWORD_ACCEPTED",request,user.id,undefined,{authenticationMethod:"PASSWORD"});if(user.administratorMfa?.enabledAt){const challenge=await createEmailChallenge(user.id,"LOGIN");const response=NextResponse.json({ok:true,mfaRequired:true,emailSent:challenge.delivered,mfaReference:challenge.reference});response.cookies.set(ADMIN_EMAIL_CHALLENGE_COOKIE,challenge.token,ADMIN_EMAIL_CHALLENGE_COOKIE_OPTIONS);return response}const created=await createSession(user.id,request,{recent:true,authenticationMethod:"MFA_ENROLLMENT"});await securityEvent("ADMIN_SESSION_CREATED",request,user.id,undefined,{sessionId:created.id,authenticationMethod:"MFA_ENROLLMENT"});return NextResponse.json({ok:true,mfaEnrollmentRequired:true})}await createSession(user.id,request,{recent:true,authenticationMethod:"PASSWORD"});return NextResponse.json({ok:true,reacceptanceRequired:(await pendingReacceptance(user.id)).length>0})}catch(error){return apiError(error)}}
