import { NextResponse } from "next/server";

const statuses: Record<string, number> = {
  UNAUTHENTICATED: 401, EMAIL_NOT_VERIFIED: 403, FORBIDDEN: 403, ACCOUNT_NOT_ACTIVE: 403, ACCOUNT_ROLE_FORBIDDEN: 403,
  RECENT_AUTH_REQUIRED: 403, MFA_REQUIRED: 403, MFA_ENROLLMENT_REQUIRED: 403,
  INVALID_MFA_CODE: 401, INVALID_MFA_CHALLENGE: 401, SESSION_NOT_FOUND: 404, SESSION_NOT_OWNED: 403, NOT_FOUND: 404,
  CUSTOMER_CLOSURE_BLOCKED: 409, CUSTOMER_ALREADY_CLOSED: 409, PRIVACY_DELETION_BLOCKED: 409,
  LEGAL_HOLD_ACTIVE: 409, RETENTION_PERIOD_ACTIVE: 409, PURGE_NOT_ELIGIBLE: 409,
  PURGE_CONFIRMATION_REQUIRED: 422, ACTIVE_SUBSCRIPTION_BLOCKS_PURGE: 409, PAYMENT_HISTORY_BLOCKS_PURGE: 409,
  UNRESOLVED_DISPUTE_BLOCKS_PURGE: 409, LAST_OWNER_REQUIRED: 409,
  STORAGE_CLEANUP_PENDING: 409, STORAGE_CLEANUP_FAILED: 503, PRODUCT_DELETION_NOT_READY: 409,
  CHECKOUT_CREATION_IN_PROGRESS: 409, TRIAL_REVOKED: 409, LEGAL_ACCEPTANCE_REQUIRED: 409,
  LEGAL_REACCEPTANCE_REQUIRED: 409, LEGAL_VERSION_IMMUTABLE: 409, LEGAL_DOCUMENTS_UNAVAILABLE: 503,
  INVALID_ORIGIN: 403, RATE_LIMITED: 429, PAYLOAD_TOO_LARGE: 413, PROVIDER_CONFIG_NOT_FOUND: 404,
  PROVIDER_CONFIG_DISABLED: 409, PROVIDER_CREDENTIAL_INVALID: 422, PROVIDER_CREDENTIAL_MISSING: 422,
  PROVIDER_ENVIRONMENT_MISMATCH: 422, PROVIDER_VALIDATION_FAILED: 422, PROVIDER_LIVE_MODE_FORBIDDEN: 403,
  PROVIDER_SOURCE_UNAVAILABLE: 503, PROVIDER_CREDENTIAL_DECRYPT_FAILED: 503,
  PAYMENT_SIGNATURE_INVALID: 400, PAYMENT_SIGNATURE_STALE: 400, PAYMENT_EVENT_REPLAY_CONFLICT: 409,
  PAYMENT_AMOUNT_MISMATCH: 409, PAYMENT_CURRENCY_MISMATCH: 409, PAYMENT_REFERENCE_MISMATCH: 409,
  PAYMENT_CHECKOUT_MISMATCH: 409, PAYMENT_MODE_MISMATCH: 409, PAYMENT_REFUND_NOT_ALLOWED: 409,
  PAYMENT_REFUND_CONFLICT: 409, PAYMENT_RECONCILIATION_REQUIRED: 409, PAYMENT_PROVIDER_UNAVAILABLE: 503,
  REFUND_CONFIRMATION_REQUIRED: 422, PAYMENT_NOT_FOUND: 404,
  BACKUP_NOT_FOUND: 404, BACKUPS_DISABLED: 409, BACKUP_NOT_EXPIRED: 409,
  INVALID_RESTORE_CONFIRMATION: 422, ISOLATED_RESTORE_NOT_CONFIGURED: 409, RESTORE_TARGET_NOT_ISOLATED: 409,
  BACKUP_STORAGE_NOT_CONFIGURED: 503, BACKUP_ENCRYPTION_NOT_CONFIGURED: 503,
};

export function apiError(error: unknown) {
  const code = error instanceof Error ? error.message : "INTERNAL_ERROR";
  const status = statuses[code] ?? 400;
  return NextResponse.json({ error: status >= 500 ? "INTERNAL_ERROR" : code }, { status });
}
