import { NextResponse } from "next/server";

export function apiError(error: unknown) {
  const code = error instanceof Error ? error.message : "INTERNAL_ERROR";
  const status = ({ UNAUTHENTICATED: 401, EMAIL_NOT_VERIFIED: 403, FORBIDDEN: 403, RECENT_AUTH_REQUIRED: 403, MFA_REQUIRED: 403, MFA_ENROLLMENT_REQUIRED: 403, INVALID_MFA_CODE: 401, INVALID_MFA_CHALLENGE: 401, SESSION_NOT_FOUND: 404, SESSION_NOT_OWNED: 403, NOT_FOUND: 404, CHECKOUT_CREATION_IN_PROGRESS: 409, TRIAL_REVOKED: 409, LEGAL_ACCEPTANCE_REQUIRED: 409, LEGAL_REACCEPTANCE_REQUIRED: 409, LEGAL_VERSION_IMMUTABLE: 409, LEGAL_DOCUMENTS_UNAVAILABLE: 503, INVALID_ORIGIN: 403, RATE_LIMITED: 429, PAYLOAD_TOO_LARGE: 413, PROVIDER_CONFIG_NOT_FOUND: 404, PROVIDER_CONFIG_DISABLED: 409, PROVIDER_CREDENTIAL_INVALID: 422, PROVIDER_CREDENTIAL_MISSING: 422, PROVIDER_ENVIRONMENT_MISMATCH: 422, PROVIDER_VALIDATION_FAILED: 422, PROVIDER_LIVE_MODE_FORBIDDEN: 403, PROVIDER_SOURCE_UNAVAILABLE: 503, PROVIDER_CREDENTIAL_DECRYPT_FAILED: 503 } as Record<string, number>)[code] ?? 400;
  const publicCode = status >= 500 ? "INTERNAL_ERROR" : code;
  return NextResponse.json({ error: publicCode }, { status });
}
