import { NextResponse } from "next/server";
import { z } from "zod";
import { createPrivateKey, createPublicKey } from "node:crypto";
import { requireRecentAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
import { assertSameOrigin } from "@/lib/security/request";
import { rateLimit } from "@/lib/security/rate-limit";
import { sha256 } from "@/lib/security/crypto";

const schema=z.object({operationId:z.string().min(8).max(128),keyId:z.string().regex(/^[A-Za-z0-9._-]{1,64}$/),algorithm:z.literal("Ed25519"),publicKey:z.string().min(32),privateKeyReference:z.string().regex(/^env:[A-Z0-9_]+$/),reason:z.string().min(1).max(500)});
function parseKey(value:string,type:"private"|"public"){const raw=value.includes("BEGIN")?value:Buffer.from(value,"base64").toString("utf8");return type==="private"?createPrivateKey(raw):createPublicKey(raw)}
export async function POST(request:Request){try{assertSameOrigin(request);const admin=await requireRecentAdmin();if(!(await rateLimit(`commercial-key-rotate:${admin.id}`,5,3600)).allowed)return NextResponse.json({error:"RATE_LIMITED"},{status:429});const input=schema.parse(await request.json());const privateValue=process.env[input.privateKeyReference.slice(4)];if(!privateValue)throw new Error("SIGNING_KEY_UNRESOLVED");const derived=createPublicKey(parseKey(privateValue,"private")).export({format:"pem",type:"spki"}).toString();const supplied=parseKey(input.publicKey,"public").export({format:"pem",type:"spki"}).toString();if(derived!==supplied)throw new Error("SIGNING_KEY_MISMATCH");const fingerprint=sha256(supplied);await db.$transaction(async tx=>{const prior=await tx.commercialLeaseOperation.findUnique({where:{operationId:input.operationId}});if(prior?.status==="COMPLETED"){const m=(prior.metadata??{}) as Record<string,unknown>;if(m.successorKeyId!==input.keyId||m.algorithm!==input.algorithm||m.publicKeyFingerprint!==fingerprint||m.privateKeyReferenceIdentity!==sha256(input.privateKeyReference)||m.reason!==input.reason)throw new Error("ROTATION_REPLAY_MISMATCH");return prior;}const active=await tx.commercialSigningKey.findMany({where:{status:"ACTIVE"}});if(active.length!==1)throw new Error(active.length?"MULTIPLE_ACTIVE_SIGNING_KEYS":"NO_ACTIVE_SIGNING_KEY");if(await tx.commercialSigningKey.findUnique({where:{keyId:input.keyId}}))throw new Error("SIGNING_KEY_EXISTS");const now=new Date();await tx.commercialSigningKey.update({where:{id:active[0]!.id},data:{status:"RETIRED",retiredAt:now,rotationReason:input.reason}});const successor=await tx.commercialSigningKey.create({data:{keyId:input.keyId,algorithm:input.algorithm,publicKey:supplied,privateKeyReference:input.privateKeyReference,status:"ACTIVE",createdBy:admin.id,rotationReason:input.reason,activatedAt:now}});const op=await tx.commercialLeaseOperation.create({data:{operationId:input.operationId,action:"KEY_ROTATION",status:"COMPLETED",metadata:{previousKeyId:active[0]!.keyId,successorKeyId:successor.keyId,algorithm:input.algorithm,publicKeyFingerprint:fingerprint,privateKeyReferenceIdentity:sha256(input.privateKeyReference),actorId:admin.id,reason:input.reason},completedAt:now}});await tx.auditLog.create({data:{actorId:admin.id,action:"COMMERCIAL_SIGNING_KEY_ROTATED",targetType:"CommercialLeaseOperation",targetId:op.id,metadata:{operationId:input.operationId,previousKeyId:active[0]!.keyId,successorKeyId:successor.keyId,reason:input.reason}}});return op}, {isolationLevel:"Serializable"});return NextResponse.json({ok:true,operationId:input.operationId},{status:201});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"INVALID_ROTATION"},{status:400})}}
